name: DCCG_NEURAL
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - compas
  - numpy
  - scipy
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - transformers
  - accelerate
  - pip
  - pip:
    - pymoo
    - diffusers
    - opencv-python
    - pillow
    - requests
